name: CD - Entrega

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  entrega:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar codigo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Validar aplicacao
        run: python -m py_compile app.py

      - name: Preparar pacote
        run: |
          mkdir pacote
          cp app.py pacote/
          cp README.md pacote/

      - name: Disponibilizar pacote
        uses: actions/upload-artifact@v4
        with:
          name: projeto-devops
          path: pacote/
